services:
  www:
    build:
      context: .
    container_name: time
    ports:
      - 8083:80
    environment:
      - VIRTUAL_HOST=time.webuxlab.com,www.time.webuxlab.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=time.webuxlab.com,www.time.webuxlab.com
      - LETSENCRYPT_SINGLE_DOMAIN_CERTS=true
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

networks:
  proxy:
    name: proxy
    external: true
