name: Continuous Delivery

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  frontend:
    name: Frontend Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Vue CLI
        run: npm install -g @vue/cli

      - name: Install Boto
        run: pip3 install boto3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ca-central-1

      - name: Deploy frontend
        run: make deploy
